CREATE SEQUENCE BOOK_ID_SEQ
    START WITH 1000
    INCREMENT BY 1
    MAXVALUE 9999;
    
CREATE SEQUENCE B_BOOKID_SEQ
    START WITH 100
    INCREMENT BY 1
    MAXVALUE 999;
    
CREATE SEQUENCE USERS_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999;
    
    
CREATE SEQUENCE R_BOOKID_SEQ
    START WITH 100
    INCREMENT BY 1
    MAXVALUE 999;
    
CREATE TABLE USERS (
    USER_ID NUMBER(5) DEFAULT USERS_SEQ.NEXTVAL PRIMARY KEY,
    USER_NAME VARCHAR2(50)
);
    
CREATE TABLE LIBRARY_BOOKS (
    BOOK_ID NUMBER(4) DEFAULT BOOK_ID_SEQ.NEXTVAL PRIMARY KEY,
    BOOK_NAME VARCHAR2(30),
    BOOK_LOC VARCHAR2(6),
    BOOK_COUNT NUMBER(2),
    RESERVED VARCHAR2(5) DEFAULT 'FALSE'
);

CREATE TABLE BORROWED_BOOKS (
    B_BOOK_ID NUMBER(3) DEFAULT B_BOOKID_SEQ.NEXTVAL PRIMARY KEY, 
    BOOK_ID NUMBER(6),
    BOOK_NAME VARCHAR2(30),
    BORROWER_ID NUMBER(5),
    
    CONSTRAINT LIB_BOOKS_FK_BBOOKS
        FOREIGN KEY (BOOK_ID) REFERENCES LIBRARY_BOOKS(BOOK_ID),
        
    CONSTRAINT USER_FK_BBOOKS
        FOREIGN KEY (BORROWER_ID) REFERENCES USERS(USER_ID)
);

ALTER TABLE BORROWED_BOOKS DROP CONSTRAINT LIB_BOOKS_FK_BBOOKS;
ALTER TABLE BORROWED_BOOKS DROP CONSTRAINT USER_FK_RBOOKS;
DROP TABLE BORROWED_BOOKS;

CREATE TABLE RESERVED_BOOKS (
    R_BOOK_ID NUMBER(3) DEFAULT R_BOOKID_SEQ.NEXTVAL PRIMARY KEY, 
    BOOK_ID NUMBER(6),
    BOOK_NAME VARCHAR2(30),
    BORROWER_ID NUMBER(5),
    
    CONSTRAINT LIB_BOOKS_FK_RBOOKS
        FOREIGN KEY (BOOK_ID) REFERENCES LIBRARY_BOOKS(BOOK_ID),
        
    CONSTRAINT USER_FK_RBOOKS
        FOREIGN KEY (BORROWER_ID) REFERENCES USERS(USER_ID)
);

ALTER TABLE RESERVED_BOOKS DROP CONSTRAINT LIB_BOOKS_FK_RBOOKS;
ALTER TABLE RESERVED_BOOKS DROP CONSTRAINT USER_FK_RBOOKS;
DROP TABLE RESERVED_BOOKS;

SELECT * FROM LIBRARY_BOOKS;
SELECT * FROM BORROWED_BOOKS;
SELECT * FROM RESERVED_BOOKS;
SELECT * FROM USERS;

UPDATE LIBRARY_BOOKS SET RESERVED = 'FALSE';

DELETE FROM BORROWED_BOOKS;
DELETE FROM RESERVED_BOOKS;

INSERT INTO LIBRARY_BOOKS (BOOK_NAME, BOOK_LOC, BOOK_COUNT) VALUES ('PLSQL Programming', 'A12R10',5);
INSERT INTO LIBRARY_BOOKS (BOOK_NAME, BOOK_LOC, BOOK_COUNT) VALUES ('WEB-Development', 'B13R20',7);
INSERT INTO LIBRARY_BOOKS (BOOK_NAME, BOOK_LOC, BOOK_COUNT) VALUES ('Canadian History', 'C14R30',9);
INSERT INTO LIBRARY_BOOKS (BOOK_NAME, BOOK_LOC, BOOK_COUNT) VALUES ('Java Programming', 'D15R40',1);
INSERT INTO LIBRARY_BOOKS (BOOK_NAME, BOOK_LOC, BOOK_COUNT) VALUES ('Cook Book', 'E16R50',10);
INSERT INTO LIBRARY_BOOKS (BOOK_NAME, BOOK_LOC, BOOK_COUNT) VALUES ('Biology-101', 'F17R60',8);
INSERT INTO LIBRARY_BOOKS (BOOK_NAME, BOOK_LOC, BOOK_COUNT) VALUES ('Physics-2', 'G18R70',5);
INSERT INTO LIBRARY_BOOKS (BOOK_NAME, BOOK_LOC, BOOK_COUNT) VALUES ('Astronomy-5vol', 'H19R80',9);
INSERT INTO LIBRARY_BOOKS (BOOK_NAME, BOOK_LOC, BOOK_COUNT) VALUES ('Game-Programming', 'I20R90',10);
INSERT INTO LIBRARY_BOOKS (BOOK_NAME, BOOK_LOC, BOOK_COUNT) VALUES ('Quantum Physics', 'J21R20',6);

UPDATE LIBRARY_BOOKS SET BOOK_COUNT = 99 WHERE BOOK_ID = 1005; 

INSERT INTO USERS (USER_NAME)VALUES ('Antonio');
INSERT INTO USERS (USER_NAME)VALUES ('Carlo');
INSERT INTO USERS (USER_NAME)VALUES ('Miha');
INSERT INTO USERS (USER_NAME)VALUES ('Cathlyn');
INSERT INTO USERS (USER_NAME)VALUES ('Samuel');
    